-- Neutral draft catalogue from the supplied project brief. No endorsements or sources.
insert into public.experts(id,name,field,country,description,status,synthetic) values
('00000000-0000-4000-8000-000000000001','Aliko Dangote','Entrepreneurship and Industry','Nigeria','A proposed entrepreneurship and industry collection connected to Aliko Dangote. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000002','Ngozi Okonjo-Iweala','Economics and Global Leadership','Nigeria','A proposed economics and global leadership collection connected to Ngozi Okonjo-Iweala. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000003','Tony Elumelu','Entrepreneurship and Investment','Nigeria','A proposed entrepreneurship and investment collection connected to Tony Elumelu. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000004','Ibukun Awosika','Leadership and Business','Nigeria','A proposed leadership and business collection connected to Ibukun Awosika. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000005','Chimamanda Ngozi Adichie','Writing and Creative Practice','Nigeria','A proposed writing and creative practice collection connected to Chimamanda Ngozi Adichie. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000006','Ndidi Nwuneli','Social Entrepreneurship and Food Systems','Nigeria','A proposed social entrepreneurship and food systems collection connected to Ndidi Nwuneli. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000007','Akinwumi Adesina','Agriculture and Development','Nigeria','A proposed agriculture and development collection connected to Akinwumi Adesina. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000008','Mo Abudu','Media and Creative Business','Nigeria','A proposed media and creative business collection connected to Mo Abudu. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000009','Iyinoluwa Aboyeji','Technology and Startups','Nigeria','A proposed technology and startups collection connected to Iyinoluwa Aboyeji. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000010','Tara Fela-Durotoye','Beauty Entrepreneurship','Nigeria','A proposed beauty entrepreneurship collection connected to Tara Fela-Durotoye. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','review',false),
('00000000-0000-4000-8000-000000000011','Strive Masiyiwa','Telecommunications and Entrepreneurship','Zimbabwe','A proposed telecommunications and entrepreneurship collection connected to Strive Masiyiwa. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000012','Fred Swaniker','Education and Leadership','Ghana','A proposed education and leadership collection connected to Fred Swaniker. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000013','Patrick Awuah Jr.','Education and Ethical Leadership','Ghana','A proposed education and ethical leadership collection connected to Patrick Awuah Jr.. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000014','Bethlehem Tilahun Alemu','Manufacturing and Entrepreneurship','Ethiopia','A proposed manufacturing and entrepreneurship collection connected to Bethlehem Tilahun Alemu. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000015','Rebecca Enonchong','Technology Entrepreneurship','Cameroon','A proposed technology entrepreneurship collection connected to Rebecca Enonchong. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000016','Juliana Rotich','Technology and Innovation','Kenya','A proposed technology and innovation collection connected to Juliana Rotich. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000017','Wanjira Mathai','Sustainability and Leadership','Kenya','A proposed sustainability and leadership collection connected to Wanjira Mathai. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000018','James Mwangi','Banking and Financial Inclusion','Kenya','A proposed banking and financial inclusion collection connected to James Mwangi. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000019','Rapelang Rabana','Technology and Education','South Africa','A proposed technology and education collection connected to Rapelang Rabana. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false),
('00000000-0000-4000-8000-000000000020','Tsitsi Masiyiwa','Social Impact and Philanthropy','Zimbabwe','A proposed social impact and philanthropy collection connected to Tsitsi Masiyiwa. Published materials have not yet been approved for use. Catalogue inclusion does not imply endorsement or authorisation.','coming',false)
on conflict(id) do nothing;
-- Fictional Amara content remains in the explicit demo adapter, not the live database.
